### ISSUE TITLE
[GHA automation security audit] Integrate zizmor into GHA

### ISSUE THREAD

**Issue by webknjaz** [ansible-collections/collection_template#86]
https://github.com/zizmorcore/workflow

Here's what can be pasted into the existing workflow definition to add a job for this:
```yaml
  zizmor:
    name: 🌈 zizmor
    permissions:
      security-events: write

    # yamllint disable-line rule:line-length
    uses: zizmorcore/workflow/.github/workflows/reusable-zizmor.yml@3bb5e95068d0f44b6d2f3f7e91379bed1d2f96a8
```
